[framework]
name = "actix-4"

[main]
urls.plaintext = "/plaintext"
urls.json = "/json"
approach = "Realistic"
classification = "Micro"
os = "Linux"
orm = "Raw"
platform = "None"
webserver = "actix-web-4"
versus = ""

# [core]
# urls.db = "/db"
# urls.query = "/queries?q="
# urls.update = "/updates?q="
# urls.fortune = "/fortunes"
# approach = "Realistic"
# classification = "Platform"
# database = "Postgres"
# database_os = "Linux"
# os = "Linux"
# orm = "Raw"
# platform = "None"
# webserver = "actix-web"
# versus = ""

# [diesel]
# urls.db = "/db"
# urls.query = "/queries?q="
# urls.update = "/updates?q="
# urls.fortune = "/fortunes"
# approach = "Realistic"
# classification = "Micro"
# database = "Postgres"
# database_os = "Linux"
# os = "Linux"
# orm = "Full"
# platform = "None"
# webserver = "actix-web"
# versus = ""

[mongodb]
# urls.db = "/db"
# urls.query = "/queries?q="
# urls.update = "/updates?q="
urls.fortune = "/fortunes"
approach = "Realistic"
classification = "Micro"
database = "MongoDB"
database_os = "Linux"
os = "Linux"
orm = "Raw"
platform = "None"
webserver = "actix-web"
versus = ""

# [raw]
# urls.plaintext = "/plaintext"
# urls.json = "/json"
# approach = "Realistic"
# classification = "Platform"
# database = "Postgres"
# database_os = "Linux"
# os = "Linux"
# orm = "Raw"
# platform = "None"
# webserver = "actix-web"
# versus = ""
